nodeLinker: node-modules

packageExtensions:
  "@babel/plugin-syntax-jsx@*":
    peerDependencies:
      "@babel/core": "*"
  "@inkline/nuxt@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
      webpack: "*"
  "@nuxtjs/eslint-module@*":
    peerDependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
